version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_rag
    ports:
      - "6333:6333"  # API REST
      - "6334:6334"  # gRPC (opcional)
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_SERVICE_HTTP_PORT=6333
      - QDRANT_SERVICE_GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: rag_network